### ISSUE TITLE
Transparent background color

### ISSUE THREAD

**Issue by abardik** [EddyVerbruggen/cordova-plugin-webviewcolor#12]
Is it possible to set a transparent background color with this plugin, like #aarrggbb (phonegap's BackgroundColor preference format) or rgba(rr, gg, bb, aa)?

**Comment by EddyVerbruggen** [comment]
Nope, not at the moment, but I guess changing that `alpha` in this line would make it possible:

https://github.com/EddyVerbruggen/cordova-plugin-webviewcolor/blob/d610c6d54696b2032b247f8e5bce8e183b1eaf44/src/ios/WebViewColor.m#L20

**Comment by abardik** [comment]
Thank you, I'll try it.

**Comment by abardik** [comment]
It works:
https://github.com/abardik/cordova-plugin-webviewcolor/blob/32f6a522bee9e047e907a4bdecf97055d022eb71/src/ios/WebViewColor.m#L20

But it will impact existing projects if merged.

**Comment by EddyVerbruggen** [comment]
Cool!

Perhaps it's best to make a copy of that native function and the [JS function](https://github.com/abardik/cordova-plugin-webviewcolor/blob/32f6a522bee9e047e907a4bdecf97055d022eb71/www/WebViewColor.js#L4) - something like `changeWithAlpha` so we don't affect current users. I'd merge a PR :)

**Comment by abardik** [comment]
Or we can accept both formats in one function. If the value is #FF112233, we'll use alpha channel. If the value is #112233 (existing projects), we'll use a regular RGB. And readme should be changed.

**Comment by EddyVerbruggen** [comment]
That would be perfect!

**Comment by abardik** [comment]
Done.

**Comment by EddyVerbruggen** [comment]
Available on npm now (version 2.1.0) - thanks for this cool feature!

**Comment by abardik** [comment]
Thanks for this and a lot of other cool plugins! I personally use background-mode, customurlscheme, insomnia, node-jwt, local-notifications and push. Thank you!
