### ISSUE TITLE
Is this on NPM?

### ISSUE THREAD

**Issue by benmcmaster** [EddyVerbruggen/cordova-plugin-webviewcolor#9]
Is this on NPM? I looked for this plugin on NPM. Couldn't find it. Evidentially Phonegap is sunsetting all plugins hosted by Phonegap Build.

**Comment by EddyVerbruggen** [comment]
Hi! AFAIK they won't remove existing plugins and since this plugin is only really useful on PGB I'm wondering why you'd need this on npm (at least until an updated version is required which I don't anticipate).

**Comment by benmcmaster** [comment]
Awesome. If they don't remove the plugins from PGB then I guess I am all good to leave that one pointed to PBG. Thanks for the reply!

**Comment by ralph-ento** [comment]
@EddyVerbruggen 

I am getting this warning message from PhoneGap recently. "This app uses plugins from the PhoneGap Build repository. These plugins won't be accessible after Nov 15th, 2016".

It is going to get removed on PGB on Nov 15th, 2016?

Are we able to get this one up on NPM before it is being removed by PGB on Nov 15th, 2016?

**Comment by EddyVerbruggen** [comment]
OK, here ya go: https://www.npmjs.com/package/cordova-plugin-webviewcolor
